### PR TITLE
created main page

### PR DESCRIPTION
**Pull request by Abhilash107**

### CODE REVIEW

**Comment by shashank-iter** [comment]
@Abhilash107 Can you add a screenshot for the page you have created ?

**Comment by Abhilash107** [comment]
Screenshot (290)

**Comment by shashank-iter** [comment]
@Abhilash107 Good Work!!

**Comment by Abhilash107** [comment]
thanks sir

**Comment by shashank-iter** [comment]
@Abhilash107 Do checkout new issues that are recently created.

**Comment by Abhilash107** [comment]
sure sir

**Pull request merged**
