### PR TITLE
UI enhanced

### PR DESCRIPTION
**Pull request by Sai-Binayak**

### CODE REVIEW

**Comment by DAddy-is-CODing2** [comment]
Screenshot (62)

**Comment by Sai-Binayak** [comment]
Screenshot (63)

**Comment by DAddy-is-CODing2** [comment]
how to fix the conflicts in the branch?

**Comment by Sai-Binayak** [comment]
is it ok to merge?

**Comment by Sai-Binayak** [comment]
@shashank-iter can you review it?

**Comment by subhranshuchoudhury** [comment]
@shashank-iter  close the PR.

**Pull request closed without merging**
