### PR TITLE
Ticket Raise Website using HTML & CSS

### PR DESCRIPTION
**Pull request by SOMNATH0904**
This Ticket raise website is simply created using HTML and CSS ...

### CODE REVIEW

**Comment by SOMNATH0904** [comment]
See the project I have created using HTML and CSS and if you like it then merge it for the Hactoberfest Event ... Thank You!

**Comment by shashank-iter** [comment]
@SOMNATH0904 Can you add the PNG for the reference so that I can evaluate the UI before merging ?

**Comment by SOMNATH0904** [comment]
[https://drive.google.com/file/d/1yAiymzRYm--NC5E-RNTeK4fzzNaEw4EG/view?usp=sharing](url)

**Comment by shashank-iter** [comment]
@SOMNATH0904 Good Work !

**Comment by shashank-iter** [comment]
Do checkout new issues that are opened recently.

**Comment by SOMNATH0904** [comment]
Thank You Bhaiya 😊 ...

**Comment by SOMNATH0904** [comment]
Okay Suree !

**Pull request merged**
